# docker-compose.yml
# This file is used to define and run multi-container Docker applications.
# It sets up a Spring Boot application with a MySQL database.
services:
  app:
    env_file:
      - .env
    image: nhan12163/tasks-management:latest
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/job_management
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root_password
      SPRING_SQL_INIT_MODE: never
      # SPRING_DATASOURCE_URL: jdbc:mysql://server.aptech.io:3307/ants
      # SPRING_DATASOURCE_USERNAME: ants_user
      # SPRING_DATASOURCE_PASSWORD: ants_password
      # SPRING_REDIS_HOST: 165.22.245.241
      # SPRING_REDIS_PORT: 6379
      # SPRING_REDIS_PASSWORD: redis_password
      # SPRING_REDIS_HOST: native-adder-5325.upstash.io
      # SPRING_REDIS_PORT: 6379
      # SPRING_REDIS_PASSWORD: ARTNAAImcDJiYzMwNjlmYWMzMjE0YjcxYTZhZmJjMzE1YWEwZGM5ZXAyNTMyNQ

    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: job_management
      # MYSQL_USER: developer
      # MYSQL_PASSWORD: developer_password
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      # This healthcheck ensures that the MySQL service is ready before the app starts.
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-proot_password']
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s
volumes:
  db_data: